import { prisma } from './db.js';
import pino from 'pino';

const logger = pino({ name: 'LocationDatabase' });

// Comprehensive Indian Locations Seed Dataset (Cities, Areas, Localities, Districts, States, Aliases)
export const INITIAL_LOCATIONS = [
  // Major Cities
  {
    name: 'Hyderabad',
    slug: 'hyderabad',
    type: 'City',
    latitude: 17.3850,
    longitude: 78.4867,
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    aliases: ['Hydrabad', 'Hyd', 'Cyberabad', 'Secunderabad'],
    searchKeywords: ['hyderabad', 'hydrabad', 'hyd', 'telangana', 'capital'],
    population: 10000000,
    listingCount: 12540,
    priority: 100,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Bangalore',
    slug: 'bangalore',
    type: 'City',
    latitude: 12.9716,
    longitude: 77.5946,
    city: 'Bangalore',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'India',
    aliases: ['Bengaluru', 'Blr', 'Bangaluru'],
    searchKeywords: ['bangalore', 'bengaluru', 'blr', 'silicon valley', 'karnataka'],
    population: 12000000,
    listingCount: 18900,
    priority: 95,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Chennai',
    slug: 'chennai',
    type: 'City',
    latitude: 13.0827,
    longitude: 80.2707,
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    aliases: ['Madras', 'Chn'],
    searchKeywords: ['chennai', 'madras', 'chn', 'tamil nadu'],
    population: 11000000,
    listingCount: 14200,
    priority: 90,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Mumbai',
    slug: 'mumbai',
    type: 'City',
    latitude: 19.0760,
    longitude: 72.8777,
    city: 'Mumbai',
    district: 'Mumbai City',
    state: 'Maharashtra',
    country: 'India',
    aliases: ['Bombay', 'Bom', 'Mumbai'],
    searchKeywords: ['mumbai', 'bombay', 'bom', 'maharashtra', 'financial capital'],
    population: 20000000,
    listingCount: 22100,
    priority: 98,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Delhi',
    slug: 'delhi',
    type: 'City',
    latitude: 28.7041,
    longitude: 77.1025,
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    aliases: ['New Delhi', 'NCR', 'DLI'],
    searchKeywords: ['delhi', 'new delhi', 'ncr', 'capital'],
    population: 19000000,
    listingCount: 19500,
    priority: 97,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Pune',
    slug: 'pune',
    type: 'City',
    latitude: 18.5204,
    longitude: 73.8567,
    city: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    aliases: ['Poona', 'PNE'],
    searchKeywords: ['pune', 'poona', 'maharashtra'],
    population: 7000000,
    listingCount: 9800,
    priority: 85,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Visakhapatnam',
    slug: 'visakhapatnam',
    type: 'City',
    latitude: 17.6868,
    longitude: 83.2185,
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Vizag', 'Waltair', 'VSKP'],
    searchKeywords: ['visakhapatnam', 'vizag', 'waltair', 'vskp', 'andhra pradesh'],
    population: 2500000,
    listingCount: 4580,
    priority: 88,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Guntur',
    slug: 'guntur',
    type: 'City',
    latitude: 16.3067,
    longitude: 80.4365,
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Gnt', 'Gunthur'],
    searchKeywords: ['guntur', 'gnt', 'andhra pradesh', 'mirchi yard'],
    population: 900000,
    listingCount: 245,
    priority: 99,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Vijayawada',
    slug: 'vijayawada',
    type: 'City',
    latitude: 16.5062,
    longitude: 80.6480,
    city: 'Vijayawada',
    district: 'NTR',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['BZA', 'Bezawada', 'Vijayawada Central'],
    searchKeywords: ['vijayawada', 'bza', 'bezawada', 'ntr', 'andhra pradesh'],
    population: 1500000,
    listingCount: 3820,
    priority: 96,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Amaravati',
    slug: 'amaravati',
    type: 'City',
    latitude: 16.5131,
    longitude: 80.5165,
    city: 'Amaravati',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Amravati', 'AP Capital', 'Amaravathi'],
    searchKeywords: ['amaravati', 'amaravathi', 'ap capital', 'guntur'],
    population: 300000,
    listingCount: 1650,
    priority: 92,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Ghaziabad',
    slug: 'ghaziabad',
    type: 'City',
    latitude: 28.6692,
    longitude: 77.4538,
    city: 'Ghaziabad',
    district: 'Ghaziabad',
    state: 'Uttar Pradesh',
    country: 'India',
    aliases: ['GZB'],
    searchKeywords: ['ghaziabad', 'ncr', 'up'],
    population: 1700000,
    listingCount: 1200,
    priority: 60,
    status: 'Active',
  },
  {
    name: 'Greater Noida',
    slug: 'greater-noida',
    type: 'City',
    latitude: 28.4744,
    longitude: 77.5040,
    city: 'Greater Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    country: 'India',
    aliases: ['Gr Noida'],
    searchKeywords: ['greater noida', 'noida', 'up'],
    population: 800000,
    listingCount: 2100,
    priority: 65,
    status: 'Active',
  },
  {
    name: 'Guwahati',
    slug: 'guwahati',
    type: 'City',
    latitude: 26.1445,
    longitude: 91.7362,
    city: 'Guwahati',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    country: 'India',
    aliases: ['Gauhati'],
    searchKeywords: ['guwahati', 'gauhati', 'assam'],
    population: 1100000,
    listingCount: 890,
    priority: 55,
    status: 'Active',
  },
  {
    name: 'Gandhinagar',
    slug: 'gandhinagar',
    type: 'City',
    latitude: 23.2156,
    longitude: 72.6369,
    city: 'Gandhinagar',
    district: 'Gandhinagar',
    state: 'Gujarat',
    country: 'India',
    aliases: ['GNR'],
    searchKeywords: ['gandhinagar', 'gujarat', 'capital'],
    population: 300000,
    listingCount: 1450,
    priority: 70,
    status: 'Active',
  },
  {
    name: 'Goa',
    slug: 'goa',
    type: 'State',
    latitude: 15.2993,
    longitude: 74.1240,
    city: 'Panaji',
    district: 'North Goa',
    state: 'Goa',
    country: 'India',
    aliases: ['Panaji', 'North Goa', 'South Goa'],
    searchKeywords: ['goa', 'panaji', 'beach'],
    population: 1500000,
    listingCount: 3100,
    priority: 80,
    status: 'Active',
    trending: true,
  },

  // Sub-Areas & Localities in Guntur
  {
    name: 'Guntur East',
    slug: 'guntur-east',
    type: 'Area',
    latitude: 16.3100,
    longitude: 80.4500,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Gnt East'],
    searchKeywords: ['guntur east', 'guntur', 'old city'],
    population: 300000,
    listingCount: 110,
    priority: 85,
    status: 'Active',
  },
  {
    name: 'Guntur West',
    slug: 'guntur-west',
    type: 'Area',
    latitude: 16.3000,
    longitude: 80.4200,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Gnt West', 'Laxmipuram'],
    searchKeywords: ['guntur west', 'laxmipuram', 'guntur'],
    population: 400000,
    listingCount: 180,
    priority: 88,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Guntur Rural',
    slug: 'guntur-rural',
    type: 'Locality',
    latitude: 16.2800,
    longitude: 80.4000,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Gnt Rural'],
    searchKeywords: ['guntur rural', 'guntur bypass'],
    population: 150000,
    listingCount: 65,
    priority: 75,
    status: 'Active',
  },
  {
    name: 'Brodipet',
    slug: 'brodipet-guntur',
    type: 'Locality',
    latitude: 16.3112,
    longitude: 80.4311,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Brodipeta'],
    searchKeywords: ['brodipet', 'brodipeta', 'guntur'],
    population: 50000,
    listingCount: 95,
    priority: 85,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Arundelpet',
    slug: 'arundelpet-guntur',
    type: 'Locality',
    latitude: 16.3050,
    longitude: 80.4390,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Arundelpeta'],
    searchKeywords: ['arundelpet', 'arundelpeta', 'guntur'],
    population: 60000,
    listingCount: 78,
    priority: 82,
    status: 'Active',
  },
  {
    name: 'Pattabhipuram',
    slug: 'pattabhipuram-guntur',
    type: 'Locality',
    latitude: 16.3180,
    longitude: 80.4220,
    parentName: 'Guntur',
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Pattabhipuram Guntur'],
    searchKeywords: ['pattabhipuram', 'guntur'],
    population: 45000,
    listingCount: 52,
    priority: 80,
    status: 'Active',
  },

  // Sub-Areas & Localities in Hyderabad
  {
    name: 'Hyderabad Central',
    slug: 'hyderabad-central',
    type: 'Area',
    latitude: 17.4000,
    longitude: 78.4700,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    aliases: ['Hyd Central', 'Abids', 'Koti'],
    searchKeywords: ['hyderabad central', 'abids', 'koti', 'hyderabad'],
    population: 600000,
    listingCount: 1450,
    priority: 90,
    status: 'Active',
  },
  {
    name: 'Hitech City',
    slug: 'hitech-city-hyderabad',
    type: 'Locality',
    latitude: 17.4435,
    longitude: 78.3772,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    country: 'India',
    aliases: ['HITEC City', 'Cyber Towers', 'Hi tech city'],
    searchKeywords: ['hitech city', 'hitec city', 'cyber towers', 'hyderabad', 'it hub'],
    population: 200000,
    listingCount: 3420,
    priority: 99,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Financial District',
    slug: 'financial-district-hyderabad',
    type: 'Locality',
    latitude: 17.4140,
    longitude: 78.3440,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    country: 'India',
    aliases: ['Nanakramguda', 'FD Hyd'],
    searchKeywords: ['financial district', 'nanakramguda', 'hyderabad', 'gachibowli'],
    population: 120000,
    listingCount: 2890,
    priority: 98,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Gachibowli',
    slug: 'gachibowli-hyderabad',
    type: 'Locality',
    latitude: 17.4401,
    longitude: 78.3489,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    country: 'India',
    aliases: ['Gachibowli Hyd'],
    searchKeywords: ['gachibowli', 'hyderabad', 'orap', 'outer ring road'],
    population: 250000,
    listingCount: 2450,
    priority: 97,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Madhapur',
    slug: 'madhapur-hyderabad',
    type: 'Locality',
    latitude: 17.4483,
    longitude: 78.3915,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    country: 'India',
    aliases: ['Madhapur IT'],
    searchKeywords: ['madhapur', 'inorbit', 'hyderabad'],
    population: 180000,
    listingCount: 2150,
    priority: 96,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Kondapur',
    slug: 'kondapur-hyderabad',
    type: 'Locality',
    latitude: 17.4600,
    longitude: 78.3660,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Rangareddy',
    state: 'Telangana',
    country: 'India',
    aliases: ['Kondapur Hyd'],
    searchKeywords: ['kondapur', 'botanical garden', 'hyderabad'],
    population: 220000,
    listingCount: 1980,
    priority: 95,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Jubilee Hills',
    slug: 'jubilee-hills-hyderabad',
    type: 'Locality',
    latitude: 17.4319,
    longitude: 78.4073,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    aliases: ['Filmnagar'],
    searchKeywords: ['jubilee hills', 'filmnagar', 'hyderabad'],
    population: 90000,
    listingCount: 890,
    priority: 94,
    status: 'Active',
    featured: true,
  },
  {
    name: 'Banjara Hills',
    slug: 'banjara-hills-hyderabad',
    type: 'Locality',
    latitude: 17.4156,
    longitude: 78.4347,
    parentName: 'Hyderabad',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    aliases: ['Road No 12'],
    searchKeywords: ['banjara hills', 'road no 12', 'hyderabad'],
    population: 110000,
    listingCount: 1120,
    priority: 93,
    status: 'Active',
    featured: true,
  },

  // Sub-Areas in Bangalore
  {
    name: 'Whitefield',
    slug: 'whitefield-bangalore',
    type: 'Locality',
    latitude: 12.9698,
    longitude: 77.7499,
    parentName: 'Bangalore',
    city: 'Bangalore',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'India',
    aliases: ['Whitefield IT'],
    searchKeywords: ['whitefield', 'bangalore', 'itpl'],
    population: 350000,
    listingCount: 3100,
    priority: 96,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Electronic City',
    slug: 'electronic-city-bangalore',
    type: 'Locality',
    latitude: 12.8399,
    longitude: 77.6770,
    parentName: 'Bangalore',
    city: 'Bangalore',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'India',
    aliases: ['E-City', 'ECity'],
    searchKeywords: ['electronic city', 'ecity', 'bangalore', 'infosys'],
    population: 280000,
    listingCount: 2750,
    priority: 95,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Koramangala',
    slug: 'koramangala-bangalore',
    type: 'Locality',
    latitude: 12.9352,
    longitude: 77.6245,
    parentName: 'Bangalore',
    city: 'Bangalore',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'India',
    aliases: ['Koramangala Hub'],
    searchKeywords: ['koramangala', 'startup hub', 'bangalore'],
    population: 180000,
    listingCount: 1840,
    priority: 94,
    status: 'Active',
    featured: true,
  },
  {
    name: 'Indiranagar',
    slug: 'indiranagar-bangalore',
    type: 'Locality',
    latitude: 12.9784,
    longitude: 77.6408,
    parentName: 'Bangalore',
    city: 'Bangalore',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'India',
    aliases: ['100ft Road Indiranagar'],
    searchKeywords: ['indiranagar', '100ft road', 'bangalore'],
    population: 150000,
    listingCount: 1420,
    priority: 93,
    status: 'Active',
  },

  // Sub-Areas in Vijayawada
  {
    name: 'Benz Circle',
    slug: 'benz-circle-vijayawada',
    type: 'Locality',
    latitude: 16.5002,
    longitude: 80.6521,
    parentName: 'Vijayawada',
    city: 'Vijayawada',
    district: 'NTR',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Benz Circle BZA'],
    searchKeywords: ['benz circle', 'vijayawada', 'bza'],
    population: 80000,
    listingCount: 820,
    priority: 90,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Tadepalli',
    slug: 'tadepalli-vijayawada',
    type: 'Locality',
    latitude: 16.4812,
    longitude: 80.6011,
    parentName: 'Vijayawada',
    city: 'Vijayawada',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Tadepalle'],
    searchKeywords: ['tadepalli', 'tadepalle', 'vijayawada', 'guntur'],
    population: 75000,
    listingCount: 640,
    priority: 88,
    status: 'Active',
    trending: true,
  },
  {
    name: 'Mangalagiri',
    slug: 'mangalagiri-guntur',
    type: 'City',
    latitude: 16.4350,
    longitude: 80.5510,
    parentName: 'Guntur',
    city: 'Mangalagiri',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['Mangalagiri AIIMS', 'APIIC Tower'],
    searchKeywords: ['mangalagiri', 'aiims', 'guntur', 'vijayawada'],
    population: 120000,
    listingCount: 980,
    priority: 91,
    status: 'Active',
    featured: true,
    trending: true,
  },
  {
    name: 'Vaddeswaram',
    slug: 'vaddeswaram-guntur',
    type: 'Locality',
    latitude: 16.4422,
    longitude: 80.6226,
    parentName: 'Guntur',
    city: 'Vaddeswaram',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    aliases: ['KL University', 'KLU', 'K L University', 'Vaddeswaram Tadepalli'],
    searchKeywords: ['vaddeswaram', 'kl university', 'klu', 'k l university', 'tadepalli', 'guntur', 'vijayawada'],
    population: 35000,
    listingCount: 420,
    priority: 95,
    status: 'Active',
    featured: true,
    trending: true,
  },
];

// In-Memory Index for ultra-fast query execution (<5ms)
let memoryLocationIndex = [...INITIAL_LOCATIONS];

// Function to calculate Haversine Distance (in km)
export function calculateDistanceKm(lat1, lon1, lat2, lon2) {
  if (!lat1 || !lon1 || !lat2 || !lon2) return null;
  const R = 6371; // Radius of Earth in KM
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

// Initialize Location Database with PostgreSQL Trigram & Memory Cache
export async function initLocationDatabase() {
  try {
    // 1. Try seeding PostgreSQL if connected
    const count = await prisma.locationItem.count().catch(() => null);
    
    if (count === 0 || count === null) {
      logger.info('Seeding initial location items into PostgreSQL database...');
      for (const loc of INITIAL_LOCATIONS) {
        await prisma.locationItem.upsert({
          where: { slug: loc.slug },
          update: loc,
          create: loc,
        }).catch(() => {});
      }
    }

    // Try executing raw PostgreSQL trigram index queries
    try {
      await prisma.$executeRawUnsafe(`CREATE EXTENSION IF NOT EXISTS pg_trgm;`);
      await prisma.$executeRawUnsafe(
        `CREATE INDEX IF NOT EXISTS idx_location_name_trgm ON "LocationItem" USING gin (name gin_trgm_ops);`
      );
      await prisma.$executeRawUnsafe(
        `CREATE INDEX IF NOT EXISTS idx_location_aliases_trgm ON "LocationItem" USING gin (aliases gin_trgm_ops);`
      );
      logger.info('PostgreSQL pg_trgm extension and GIN trigram indexes verified.');
    } catch (dbErr) {
      logger.warn({ err: dbErr.message }, 'PostgreSQL raw query for pg_trgm skipped (hybrid/offline database mode active).');
    }

    // Refresh memory cache from DB if DB available, otherwise fallback to INITIAL_LOCATIONS
    const dbLocations = await prisma.locationItem.findMany({
      where: { status: 'Active' },
      orderBy: [{ priority: 'desc' }, { listingCount: 'desc' }]
    }).catch(() => []);

    if (dbLocations && dbLocations.length > 0) {
      memoryLocationIndex = dbLocations;
    }
  } catch (err) {
    logger.error({ err: err.message }, 'Location database initialization completed with fallback index.');
  }
}

// Export getter for current memory cache
export function getMemoryLocations() {
  return memoryLocationIndex;
}

// Export memory location pusher for live updates
export function updateMemoryLocations(newList) {
  memoryLocationIndex = newList;
}
